version: "3"

services:
    loki:
        image: grafana/loki:master
        command: -config.file=/etc/loki/local-config.yaml
        networks:
            - world
            - grafana-loki
        ports:
            - "4100:3100"  # Expose the Loki API port
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus:/app.cfg
        networks:
            - world
            - grafana-prometheus
        command: >-
            --config.file=/app.cfg/prometheus.yml
            --storage.tsdb.path=/prometheus
            --web.console.libraries=/usr/share/prometheus/console_libraries
            --web.console.templates=/usr/share/prometheus/consoles

    grafana:
        depends_on:
            - loki
        image: grafana/grafana
        ports:
            - "4000:3000"
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: test
            GF_PATHS_PROVISIONING: '/app.cfg/provisioning'
        volumes:
            - ./grafana:/app.cfg
        networks:
            - world
            - grafana-loki
            - grafana-prometheus

networks:
    world:
    grafana-loki:
        internal: true
    grafana-prometheus:
        internal: true
